#------------------------------------------------------------------------------
# RESOURCE USAGE (except WAL)
#------------------------------------------------------------------------------

# - Memory -

shared_buffers = 1536MB                 # min 128kB
work_mem = 32MB                      # min 64kB
maintenance_work_mem = 512MB            # min 64kB

# - Asynchronous Behavior -

effective_io_concurrency = 200         # 1-1000; 0 disables prefetching
max_worker_processes = 6              # (change requires restart)
max_parallel_workers_per_gather = 3    # limited by max_parallel_workers
max_parallel_maintenance_workers = 2   # limited by max_parallel_workers
max_parallel_workers = 6              # number of max_worker_processes that

#------------------------------------------------------------------------------
# WRITE-AHEAD LOG
#------------------------------------------------------------------------------

wal_buffers = 4MB                     # min 32kB, -1 sets based on shared_buffers

# - Checkpoints -

checkpoint_timeout = 5min             # range 30s-1d
max_wal_size = 1GB
min_wal_size = 64MB

#------------------------------------------------------------------------------
# QUERY TUNING
#------------------------------------------------------------------------------

#seq_page_cost = 1.0                   # measured on an arbitrary scale
random_page_cost = 1.1                 # same scale as above
parallel_setup_cost = 500.0            # same scale as above
parallel_tuple_cost = 0.05             # same scale as above
effective_cache_size = 4608MB
