#!/usr/bin/env bash

set -euo pipefail

python /app/manage.py collectstatic --noinput

exec gunicorn --max-requests 3000 --max-requests-jitter 100 config.wsgi:application --bind 0.0.0.0:${PORT:-5000} --chdir=/app
