# syntax=docker/dockerfile:1.22.0
FROM docker.io/traefik:3.6.11
RUN mkdir -p /etc/traefik/acme \
  && touch /etc/traefik/acme/acme.json \
  && chmod 600 /etc/traefik/acme/acme.json
COPY ./compose/stage/traefik/traefik.yml /etc/traefik
