# Generated by Django 4.2.6 on 2023-11-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SuccessfulEmailChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        help_text="The email of the `User` before the email change was made.",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        help_text="The email of the `User` after the email change was made.",
                        max_length=254,
                        verbose_name="To Email",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        help_text="The timestamp of the latest request for the change before the successful email change was made.",
                        verbose_name="Requested At",
                    ),
                ),
                (
                    "successfully_changed_at",
                    models.DateTimeField(
                        help_text="The timestamp of when the email was successfully changed.",
                        verbose_name="Successfully Changed At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successful_email_changes",
                        related_query_name="successful_email_change",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Successful Email Change",
                "verbose_name_plural": "Successful Email Changes",
            },
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="The email of the `User` at the time of the request (or blank if no request has been made yet).",
                        max_length=254,
                        verbose_name="From Email",
                    ),
                ),
                (
                    "to_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="The email that the `User` is requesting to change to (or blank if no request has been made yet).",
                        max_length=254,
                        verbose_name="To Email",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text='The timestamp of the latest time the user requested to change their email here from "From Email" to "To Email".',
                        null=True,
                        verbose_name="Requested At",
                    ),
                ),
                (
                    "successfully_changed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text='The timestamp of when the email was successfully changed from "From Email" to "To Email" (if it was successfully changed).',
                        null=True,
                        verbose_name="Successfully Changed At",
                    ),
                ),
                (
                    "last_requested_a_new_from_or_to_email_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text='The timestamp of the latest time the user requested a new email change to a different "To Email" and/or from a different "From Email".',
                        null=True,
                        verbose_name='Last Requested a New "From Email" or "To Email" At',
                    ),
                ),
                (
                    "num_times_requested_a_new_from_or_to_email",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        help_text='The number of times the user requested a new email change to a different "To Email" and/or from a different "From Email".',
                        verbose_name='Number of Times a New "From Email" or "To Email" Has Been Requested',
                    ),
                ),
                (
                    "last_sent_a_change_email_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Last Sent a Change Email At",
                    ),
                ),
                (
                    "num_times_sent_a_change_email",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        verbose_name="Number of Times a Change Email Has Been Sent",
                    ),
                ),
                (
                    "last_successfully_changed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="Last Successfully Changed At",
                    ),
                ),
                (
                    "num_times_email_successfully_changed",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        editable=False,
                        verbose_name="Number of Times an Email Has Been Successfully Changed",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_request",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Change Request",
                "verbose_name_plural": "Email Change Requests",
            },
        ),
        migrations.AddConstraint(
            model_name="emailchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", -1), _negated=True), name="ath__ecr__id_not_-1_cc"
            ),
        ),
    ]
