from __future__ import annotations

from typing import Final

LOCAL_SSH_ALIAS: Final = "..."

SERVER_IP: Final = "..."
SSH_PORT: Final = -1
POSTGRES_PORT: Final = -1
SERVER_MAIN_APP_DOMAIN = "..."

POSTGRES_ROLE_BETTER_BASE_BACKEND_NAME: Final = "better_base_backend"
POSTGRES_ROLE_BETTER_BASE_BACKEND_PASSWORD: Final = "..."

POSTGRES_ROLE_BETTER_BASE_EXTERNAL_NAME: Final = "better_base_external"
POSTGRES_ROLE_BETTER_BASE_EXTERNAL_PASSWORD: Final = "..."

CLOUDFLARE_BACKUPS_R2_SECRET_TOKEN: Final = "..."
CLOUDFLARE_BACKUPS_S3_COMPAT_ACCESS_KEY_ID: Final = "..."
CLOUDFLARE_BACKUPS_S3_COMPAT_SECRET_ACCESS_KEY: Final = "..."
CLOUDFLARE_BACKUPS_S3_COMPAT_JURISDICTION_ENDPOINT: Final = "..."

CLOUDFLARE_R2_SECRET_TOKEN: Final = "..."
CLOUDFLARE_R2_S3_COMPAT_ACCESS_KEY_ID: Final = "..."
CLOUDFLARE_R2_S3_COMPAT_SECRET_ACCESS_KEY: Final = "..."
CLOUDFLARE_R2_S3_COMPAT_JURISDICTION_ENDPOINT: Final = "..."

MAILGUN_DOMAIN: Final = "..."
MAILGUN_API_KEY: Final = "..."
MAILGUN_WEBHOOK_SIGNING_KEY: Final = "..."

SENTRY_AUTH_TOKEN: Final = "..."
SENTRY_DSN: Final = "..."

APP_POSTGRES_DATABASE_URL: Final = "..."
APP_POSTGRES_HOST: Final = "..."
APP_POSTGRES_PORT: Final = "..."
APP_POSTGRES_DB: Final = "..."
APP_POSTGRES_USER: Final = "..."
APP_POSTGRES_PASSWORD: Final = "..."

EXTERNAL_POSTGRES_DATABASE_URL: Final = "..."
EXTERNAL_POSTGRES_HOST: Final = "..."
EXTERNAL_POSTGRES_PORT: Final = "..."
EXTERNAL_POSTGRES_DB: Final = "..."
EXTERNAL_POSTGRES_USER: Final = "..."
EXTERNAL_POSTGRES_PASSWORD: Final = "..."
