/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryTestRouteImport } from './routes/sentry-test'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FollowInvitationIndexRouteImport } from './routes/follow-invitation/index'
import { Route as FollowInvitationErrorRouteImport } from './routes/follow-invitation/error'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthVerifyEmailSuccessRouteImport } from './routes/auth/verify-email/success'
import { Route as AuthVerifyEmailSentRouteImport } from './routes/auth/verify-email/sent'
import { Route as AuthVerifyEmailResendRouteImport } from './routes/auth/verify-email/resend'
import { Route as AuthSignupFromInvitationRouteImport } from './routes/auth/signup/from-invitation'
import { Route as AuthSignupCompleteRouteImport } from './routes/auth/signup/complete'
import { Route as AuthResetPasswordSentRouteImport } from './routes/auth/reset-password/sent'
import { Route as AuthLoginFromInvitationRouteImport } from './routes/auth/login/from-invitation'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsLogoutRouteImport } from './routes/_auth/settings/logout'
import { Route as AuthSettingsAccountsRouteImport } from './routes/_auth/settings/accounts'
import { Route as AuthAccountsAccountIdRouteImport } from './routes/_auth/accounts/$accountId'
import { Route as AuthSignupVerifyEmailIndexRouteImport } from './routes/auth/signup/verify-email/index'
import { Route as AuthAccountsAccountIdIndexRouteImport } from './routes/_auth/accounts/$accountId/index'
import { Route as AuthVerifyEmailConfirmSuccessRouteImport } from './routes/auth/verify-email/confirm.success'
import { Route as AuthSignupVerifyEmailSuccessRouteImport } from './routes/auth/signup/verify-email/success'
import { Route as AuthChangeEmailConfirmSuccessRouteImport } from './routes/auth/change-email/confirm.success'
import { Route as AuthAccountsAccountIdTeamRouteImport } from './routes/_auth/accounts/$accountId/team'
import { Route as AuthAccountsAccountIdSettingsRouteImport } from './routes/_auth/accounts/$accountId/settings'
import { Route as AuthVerifyEmailConfirmUidb64SecretTokenIndexRouteImport } from './routes/auth/verify-email/confirm.$uidb64.$secretToken/index'
import { Route as AuthResetPasswordConfirmUidb64SecretTokenIndexRouteImport } from './routes/auth/reset-password/confirm.$uidb64.$secretToken/index'
import { Route as AuthChangeEmailConfirmUidb64SecretTokenIndexRouteImport } from './routes/auth/change-email/confirm.$uidb64.$secretToken/index'
import { Route as AuthVerifyEmailConfirmUidb64SecretTokenInvalidRouteImport } from './routes/auth/verify-email/confirm.$uidb64.$secretToken/invalid'
import { Route as AuthResetPasswordConfirmUidb64SecretTokenInvalidRouteImport } from './routes/auth/reset-password/confirm.$uidb64.$secretToken/invalid'
import { Route as AuthChangeEmailConfirmUidb64SecretTokenInvalidRouteImport } from './routes/auth/change-email/confirm.$uidb64.$secretToken/invalid'

const SentryTestRoute = SentryTestRouteImport.update({
  id: '/sentry-test',
  path: '/sentry-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowInvitationIndexRoute = FollowInvitationIndexRouteImport.update({
  id: '/follow-invitation/',
  path: '/follow-invitation/',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowInvitationErrorRoute = FollowInvitationErrorRouteImport.update({
  id: '/follow-invitation/error',
  path: '/follow-invitation/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/auth/signup/',
  path: '/auth/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthVerifyEmailSuccessRoute = AuthVerifyEmailSuccessRouteImport.update({
  id: '/auth/verify-email/success',
  path: '/auth/verify-email/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailSentRoute = AuthVerifyEmailSentRouteImport.update({
  id: '/auth/verify-email/sent',
  path: '/auth/verify-email/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailResendRoute = AuthVerifyEmailResendRouteImport.update({
  id: '/auth/verify-email/resend',
  path: '/auth/verify-email/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupFromInvitationRoute =
  AuthSignupFromInvitationRouteImport.update({
    id: '/auth/signup/from-invitation',
    path: '/auth/signup/from-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignupCompleteRoute = AuthSignupCompleteRouteImport.update({
  id: '/auth/signup/complete',
  path: '/auth/signup/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordSentRoute = AuthResetPasswordSentRouteImport.update({
  id: '/auth/reset-password/sent',
  path: '/auth/reset-password/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginFromInvitationRoute = AuthLoginFromInvitationRouteImport.update({
  id: '/auth/login/from-invitation',
  path: '/auth/login/from-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsLogoutRoute = AuthSettingsLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthSettingsAccountsRoute = AuthSettingsAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthSettingsRoute,
} as any)
const AuthAccountsAccountIdRoute = AuthAccountsAccountIdRouteImport.update({
  id: '/accounts/$accountId',
  path: '/accounts/$accountId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupVerifyEmailIndexRoute =
  AuthSignupVerifyEmailIndexRouteImport.update({
    id: '/auth/signup/verify-email/',
    path: '/auth/signup/verify-email/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAccountsAccountIdIndexRoute =
  AuthAccountsAccountIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAccountsAccountIdRoute,
  } as any)
const AuthVerifyEmailConfirmSuccessRoute =
  AuthVerifyEmailConfirmSuccessRouteImport.update({
    id: '/auth/verify-email/confirm/success',
    path: '/auth/verify-email/confirm/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSignupVerifyEmailSuccessRoute =
  AuthSignupVerifyEmailSuccessRouteImport.update({
    id: '/auth/signup/verify-email/success',
    path: '/auth/signup/verify-email/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthChangeEmailConfirmSuccessRoute =
  AuthChangeEmailConfirmSuccessRouteImport.update({
    id: '/auth/change-email/confirm/success',
    path: '/auth/change-email/confirm/success',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAccountsAccountIdTeamRoute =
  AuthAccountsAccountIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthAccountsAccountIdRoute,
  } as any)
const AuthAccountsAccountIdSettingsRoute =
  AuthAccountsAccountIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthAccountsAccountIdRoute,
  } as any)
const AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute =
  AuthVerifyEmailConfirmUidb64SecretTokenIndexRouteImport.update({
    id: '/auth/verify-email/confirm/$uidb64/$secretToken/',
    path: '/auth/verify-email/confirm/$uidb64/$secretToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordConfirmUidb64SecretTokenIndexRoute =
  AuthResetPasswordConfirmUidb64SecretTokenIndexRouteImport.update({
    id: '/auth/reset-password/confirm/$uidb64/$secretToken/',
    path: '/auth/reset-password/confirm/$uidb64/$secretToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthChangeEmailConfirmUidb64SecretTokenIndexRoute =
  AuthChangeEmailConfirmUidb64SecretTokenIndexRouteImport.update({
    id: '/auth/change-email/confirm/$uidb64/$secretToken/',
    path: '/auth/change-email/confirm/$uidb64/$secretToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute =
  AuthVerifyEmailConfirmUidb64SecretTokenInvalidRouteImport.update({
    id: '/auth/verify-email/confirm/$uidb64/$secretToken/invalid',
    path: '/auth/verify-email/confirm/$uidb64/$secretToken/invalid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute =
  AuthResetPasswordConfirmUidb64SecretTokenInvalidRouteImport.update({
    id: '/auth/reset-password/confirm/$uidb64/$secretToken/invalid',
    path: '/auth/reset-password/confirm/$uidb64/$secretToken/invalid',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute =
  AuthChangeEmailConfirmUidb64SecretTokenInvalidRouteImport.update({
    id: '/auth/change-email/confirm/$uidb64/$secretToken/invalid',
    path: '/auth/change-email/confirm/$uidb64/$secretToken/invalid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sentry-test': typeof SentryTestRoute
  '/settings': typeof AuthSettingsRouteWithChildren
  '/follow-invitation/error': typeof FollowInvitationErrorRoute
  '/follow-invitation/': typeof FollowInvitationIndexRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdRouteWithChildren
  '/settings/accounts': typeof AuthSettingsAccountsRoute
  '/settings/logout': typeof AuthSettingsLogoutRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/auth/login/from-invitation': typeof AuthLoginFromInvitationRoute
  '/auth/reset-password/sent': typeof AuthResetPasswordSentRoute
  '/auth/signup/complete': typeof AuthSignupCompleteRoute
  '/auth/signup/from-invitation': typeof AuthSignupFromInvitationRoute
  '/auth/verify-email/resend': typeof AuthVerifyEmailResendRoute
  '/auth/verify-email/sent': typeof AuthVerifyEmailSentRoute
  '/auth/verify-email/success': typeof AuthVerifyEmailSuccessRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/accounts/$accountId/settings': typeof AuthAccountsAccountIdSettingsRoute
  '/accounts/$accountId/team': typeof AuthAccountsAccountIdTeamRoute
  '/auth/change-email/confirm/success': typeof AuthChangeEmailConfirmSuccessRoute
  '/auth/signup/verify-email/success': typeof AuthSignupVerifyEmailSuccessRoute
  '/auth/verify-email/confirm/success': typeof AuthVerifyEmailConfirmSuccessRoute
  '/accounts/$accountId/': typeof AuthAccountsAccountIdIndexRoute
  '/auth/signup/verify-email/': typeof AuthSignupVerifyEmailIndexRoute
  '/auth/change-email/confirm/$uidb64/$secretToken/invalid': typeof AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken/invalid': typeof AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken/invalid': typeof AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/change-email/confirm/$uidb64/$secretToken/': typeof AuthChangeEmailConfirmUidb64SecretTokenIndexRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken/': typeof AuthResetPasswordConfirmUidb64SecretTokenIndexRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken/': typeof AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sentry-test': typeof SentryTestRoute
  '/follow-invitation/error': typeof FollowInvitationErrorRoute
  '/follow-invitation': typeof FollowInvitationIndexRoute
  '/settings/accounts': typeof AuthSettingsAccountsRoute
  '/settings/logout': typeof AuthSettingsLogoutRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/auth/login/from-invitation': typeof AuthLoginFromInvitationRoute
  '/auth/reset-password/sent': typeof AuthResetPasswordSentRoute
  '/auth/signup/complete': typeof AuthSignupCompleteRoute
  '/auth/signup/from-invitation': typeof AuthSignupFromInvitationRoute
  '/auth/verify-email/resend': typeof AuthVerifyEmailResendRoute
  '/auth/verify-email/sent': typeof AuthVerifyEmailSentRoute
  '/auth/verify-email/success': typeof AuthVerifyEmailSuccessRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/accounts/$accountId/settings': typeof AuthAccountsAccountIdSettingsRoute
  '/accounts/$accountId/team': typeof AuthAccountsAccountIdTeamRoute
  '/auth/change-email/confirm/success': typeof AuthChangeEmailConfirmSuccessRoute
  '/auth/signup/verify-email/success': typeof AuthSignupVerifyEmailSuccessRoute
  '/auth/verify-email/confirm/success': typeof AuthVerifyEmailConfirmSuccessRoute
  '/accounts/$accountId': typeof AuthAccountsAccountIdIndexRoute
  '/auth/signup/verify-email': typeof AuthSignupVerifyEmailIndexRoute
  '/auth/change-email/confirm/$uidb64/$secretToken/invalid': typeof AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken/invalid': typeof AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken/invalid': typeof AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/change-email/confirm/$uidb64/$secretToken': typeof AuthChangeEmailConfirmUidb64SecretTokenIndexRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken': typeof AuthResetPasswordConfirmUidb64SecretTokenIndexRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken': typeof AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/sentry-test': typeof SentryTestRoute
  '/_auth/settings': typeof AuthSettingsRouteWithChildren
  '/follow-invitation/error': typeof FollowInvitationErrorRoute
  '/follow-invitation/': typeof FollowInvitationIndexRoute
  '/_auth/accounts/$accountId': typeof AuthAccountsAccountIdRouteWithChildren
  '/_auth/settings/accounts': typeof AuthSettingsAccountsRoute
  '/_auth/settings/logout': typeof AuthSettingsLogoutRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/auth/login/from-invitation': typeof AuthLoginFromInvitationRoute
  '/auth/reset-password/sent': typeof AuthResetPasswordSentRoute
  '/auth/signup/complete': typeof AuthSignupCompleteRoute
  '/auth/signup/from-invitation': typeof AuthSignupFromInvitationRoute
  '/auth/verify-email/resend': typeof AuthVerifyEmailResendRoute
  '/auth/verify-email/sent': typeof AuthVerifyEmailSentRoute
  '/auth/verify-email/success': typeof AuthVerifyEmailSuccessRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/_auth/accounts/$accountId/settings': typeof AuthAccountsAccountIdSettingsRoute
  '/_auth/accounts/$accountId/team': typeof AuthAccountsAccountIdTeamRoute
  '/auth/change-email/confirm/success': typeof AuthChangeEmailConfirmSuccessRoute
  '/auth/signup/verify-email/success': typeof AuthSignupVerifyEmailSuccessRoute
  '/auth/verify-email/confirm/success': typeof AuthVerifyEmailConfirmSuccessRoute
  '/_auth/accounts/$accountId/': typeof AuthAccountsAccountIdIndexRoute
  '/auth/signup/verify-email/': typeof AuthSignupVerifyEmailIndexRoute
  '/auth/change-email/confirm/$uidb64/$secretToken/invalid': typeof AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken/invalid': typeof AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken/invalid': typeof AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute
  '/auth/change-email/confirm/$uidb64/$secretToken/': typeof AuthChangeEmailConfirmUidb64SecretTokenIndexRoute
  '/auth/reset-password/confirm/$uidb64/$secretToken/': typeof AuthResetPasswordConfirmUidb64SecretTokenIndexRoute
  '/auth/verify-email/confirm/$uidb64/$secretToken/': typeof AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sentry-test'
    | '/settings'
    | '/follow-invitation/error'
    | '/follow-invitation/'
    | '/accounts/$accountId'
    | '/settings/accounts'
    | '/settings/logout'
    | '/settings/profile'
    | '/auth/login/from-invitation'
    | '/auth/reset-password/sent'
    | '/auth/signup/complete'
    | '/auth/signup/from-invitation'
    | '/auth/verify-email/resend'
    | '/auth/verify-email/sent'
    | '/auth/verify-email/success'
    | '/settings/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/auth/verify-email/'
    | '/accounts/$accountId/settings'
    | '/accounts/$accountId/team'
    | '/auth/change-email/confirm/success'
    | '/auth/signup/verify-email/success'
    | '/auth/verify-email/confirm/success'
    | '/accounts/$accountId/'
    | '/auth/signup/verify-email/'
    | '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
    | '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/change-email/confirm/$uidb64/$secretToken/'
    | '/auth/reset-password/confirm/$uidb64/$secretToken/'
    | '/auth/verify-email/confirm/$uidb64/$secretToken/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sentry-test'
    | '/follow-invitation/error'
    | '/follow-invitation'
    | '/settings/accounts'
    | '/settings/logout'
    | '/settings/profile'
    | '/auth/login/from-invitation'
    | '/auth/reset-password/sent'
    | '/auth/signup/complete'
    | '/auth/signup/from-invitation'
    | '/auth/verify-email/resend'
    | '/auth/verify-email/sent'
    | '/auth/verify-email/success'
    | '/settings'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/accounts/$accountId/settings'
    | '/accounts/$accountId/team'
    | '/auth/change-email/confirm/success'
    | '/auth/signup/verify-email/success'
    | '/auth/verify-email/confirm/success'
    | '/accounts/$accountId'
    | '/auth/signup/verify-email'
    | '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
    | '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/change-email/confirm/$uidb64/$secretToken'
    | '/auth/reset-password/confirm/$uidb64/$secretToken'
    | '/auth/verify-email/confirm/$uidb64/$secretToken'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/sentry-test'
    | '/_auth/settings'
    | '/follow-invitation/error'
    | '/follow-invitation/'
    | '/_auth/accounts/$accountId'
    | '/_auth/settings/accounts'
    | '/_auth/settings/logout'
    | '/_auth/settings/profile'
    | '/auth/login/from-invitation'
    | '/auth/reset-password/sent'
    | '/auth/signup/complete'
    | '/auth/signup/from-invitation'
    | '/auth/verify-email/resend'
    | '/auth/verify-email/sent'
    | '/auth/verify-email/success'
    | '/_auth/settings/'
    | '/auth/login/'
    | '/auth/reset-password/'
    | '/auth/signup/'
    | '/auth/verify-email/'
    | '/_auth/accounts/$accountId/settings'
    | '/_auth/accounts/$accountId/team'
    | '/auth/change-email/confirm/success'
    | '/auth/signup/verify-email/success'
    | '/auth/verify-email/confirm/success'
    | '/_auth/accounts/$accountId/'
    | '/auth/signup/verify-email/'
    | '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
    | '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
    | '/auth/change-email/confirm/$uidb64/$secretToken/'
    | '/auth/reset-password/confirm/$uidb64/$secretToken/'
    | '/auth/verify-email/confirm/$uidb64/$secretToken/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SentryTestRoute: typeof SentryTestRoute
  FollowInvitationErrorRoute: typeof FollowInvitationErrorRoute
  FollowInvitationIndexRoute: typeof FollowInvitationIndexRoute
  AuthLoginFromInvitationRoute: typeof AuthLoginFromInvitationRoute
  AuthResetPasswordSentRoute: typeof AuthResetPasswordSentRoute
  AuthSignupCompleteRoute: typeof AuthSignupCompleteRoute
  AuthSignupFromInvitationRoute: typeof AuthSignupFromInvitationRoute
  AuthVerifyEmailResendRoute: typeof AuthVerifyEmailResendRoute
  AuthVerifyEmailSentRoute: typeof AuthVerifyEmailSentRoute
  AuthVerifyEmailSuccessRoute: typeof AuthVerifyEmailSuccessRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
  AuthChangeEmailConfirmSuccessRoute: typeof AuthChangeEmailConfirmSuccessRoute
  AuthSignupVerifyEmailSuccessRoute: typeof AuthSignupVerifyEmailSuccessRoute
  AuthVerifyEmailConfirmSuccessRoute: typeof AuthVerifyEmailConfirmSuccessRoute
  AuthSignupVerifyEmailIndexRoute: typeof AuthSignupVerifyEmailIndexRoute
  AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute: typeof AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute
  AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute: typeof AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute
  AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute: typeof AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute
  AuthChangeEmailConfirmUidb64SecretTokenIndexRoute: typeof AuthChangeEmailConfirmUidb64SecretTokenIndexRoute
  AuthResetPasswordConfirmUidb64SecretTokenIndexRoute: typeof AuthResetPasswordConfirmUidb64SecretTokenIndexRoute
  AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute: typeof AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-test': {
      id: '/sentry-test'
      path: '/sentry-test'
      fullPath: '/sentry-test'
      preLoaderRoute: typeof SentryTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-invitation/': {
      id: '/follow-invitation/'
      path: '/follow-invitation'
      fullPath: '/follow-invitation/'
      preLoaderRoute: typeof FollowInvitationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-invitation/error': {
      id: '/follow-invitation/error'
      path: '/follow-invitation/error'
      fullPath: '/follow-invitation/error'
      preLoaderRoute: typeof FollowInvitationErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/auth/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/auth/verify-email/success': {
      id: '/auth/verify-email/success'
      path: '/auth/verify-email/success'
      fullPath: '/auth/verify-email/success'
      preLoaderRoute: typeof AuthVerifyEmailSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/sent': {
      id: '/auth/verify-email/sent'
      path: '/auth/verify-email/sent'
      fullPath: '/auth/verify-email/sent'
      preLoaderRoute: typeof AuthVerifyEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/resend': {
      id: '/auth/verify-email/resend'
      path: '/auth/verify-email/resend'
      fullPath: '/auth/verify-email/resend'
      preLoaderRoute: typeof AuthVerifyEmailResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/from-invitation': {
      id: '/auth/signup/from-invitation'
      path: '/auth/signup/from-invitation'
      fullPath: '/auth/signup/from-invitation'
      preLoaderRoute: typeof AuthSignupFromInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/complete': {
      id: '/auth/signup/complete'
      path: '/auth/signup/complete'
      fullPath: '/auth/signup/complete'
      preLoaderRoute: typeof AuthSignupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/sent': {
      id: '/auth/reset-password/sent'
      path: '/auth/reset-password/sent'
      fullPath: '/auth/reset-password/sent'
      preLoaderRoute: typeof AuthResetPasswordSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/from-invitation': {
      id: '/auth/login/from-invitation'
      path: '/auth/login/from-invitation'
      fullPath: '/auth/login/from-invitation'
      preLoaderRoute: typeof AuthLoginFromInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/logout': {
      id: '/_auth/settings/logout'
      path: '/logout'
      fullPath: '/settings/logout'
      preLoaderRoute: typeof AuthSettingsLogoutRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/settings/accounts': {
      id: '/_auth/settings/accounts'
      path: '/accounts'
      fullPath: '/settings/accounts'
      preLoaderRoute: typeof AuthSettingsAccountsRouteImport
      parentRoute: typeof AuthSettingsRoute
    }
    '/_auth/accounts/$accountId': {
      id: '/_auth/accounts/$accountId'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AuthAccountsAccountIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup/verify-email/': {
      id: '/auth/signup/verify-email/'
      path: '/auth/signup/verify-email'
      fullPath: '/auth/signup/verify-email/'
      preLoaderRoute: typeof AuthSignupVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accounts/$accountId/': {
      id: '/_auth/accounts/$accountId/'
      path: '/'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AuthAccountsAccountIdIndexRouteImport
      parentRoute: typeof AuthAccountsAccountIdRoute
    }
    '/auth/verify-email/confirm/success': {
      id: '/auth/verify-email/confirm/success'
      path: '/auth/verify-email/confirm/success'
      fullPath: '/auth/verify-email/confirm/success'
      preLoaderRoute: typeof AuthVerifyEmailConfirmSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup/verify-email/success': {
      id: '/auth/signup/verify-email/success'
      path: '/auth/signup/verify-email/success'
      fullPath: '/auth/signup/verify-email/success'
      preLoaderRoute: typeof AuthSignupVerifyEmailSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-email/confirm/success': {
      id: '/auth/change-email/confirm/success'
      path: '/auth/change-email/confirm/success'
      fullPath: '/auth/change-email/confirm/success'
      preLoaderRoute: typeof AuthChangeEmailConfirmSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/accounts/$accountId/team': {
      id: '/_auth/accounts/$accountId/team'
      path: '/team'
      fullPath: '/accounts/$accountId/team'
      preLoaderRoute: typeof AuthAccountsAccountIdTeamRouteImport
      parentRoute: typeof AuthAccountsAccountIdRoute
    }
    '/_auth/accounts/$accountId/settings': {
      id: '/_auth/accounts/$accountId/settings'
      path: '/settings'
      fullPath: '/accounts/$accountId/settings'
      preLoaderRoute: typeof AuthAccountsAccountIdSettingsRouteImport
      parentRoute: typeof AuthAccountsAccountIdRoute
    }
    '/auth/verify-email/confirm/$uidb64/$secretToken/': {
      id: '/auth/verify-email/confirm/$uidb64/$secretToken/'
      path: '/auth/verify-email/confirm/$uidb64/$secretToken'
      fullPath: '/auth/verify-email/confirm/$uidb64/$secretToken/'
      preLoaderRoute: typeof AuthVerifyEmailConfirmUidb64SecretTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/confirm/$uidb64/$secretToken/': {
      id: '/auth/reset-password/confirm/$uidb64/$secretToken/'
      path: '/auth/reset-password/confirm/$uidb64/$secretToken'
      fullPath: '/auth/reset-password/confirm/$uidb64/$secretToken/'
      preLoaderRoute: typeof AuthResetPasswordConfirmUidb64SecretTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-email/confirm/$uidb64/$secretToken/': {
      id: '/auth/change-email/confirm/$uidb64/$secretToken/'
      path: '/auth/change-email/confirm/$uidb64/$secretToken'
      fullPath: '/auth/change-email/confirm/$uidb64/$secretToken/'
      preLoaderRoute: typeof AuthChangeEmailConfirmUidb64SecretTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/confirm/$uidb64/$secretToken/invalid': {
      id: '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
      path: '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
      fullPath: '/auth/verify-email/confirm/$uidb64/$secretToken/invalid'
      preLoaderRoute: typeof AuthVerifyEmailConfirmUidb64SecretTokenInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/confirm/$uidb64/$secretToken/invalid': {
      id: '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
      path: '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
      fullPath: '/auth/reset-password/confirm/$uidb64/$secretToken/invalid'
      preLoaderRoute: typeof AuthResetPasswordConfirmUidb64SecretTokenInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-email/confirm/$uidb64/$secretToken/invalid': {
      id: '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
      path: '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
      fullPath: '/auth/change-email/confirm/$uidb64/$secretToken/invalid'
      preLoaderRoute: typeof AuthChangeEmailConfirmUidb64SecretTokenInvalidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthSettingsRouteChildren {
  AuthSettingsAccountsRoute: typeof AuthSettingsAccountsRoute
  AuthSettingsLogoutRoute: typeof AuthSettingsLogoutRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsAccountsRoute: AuthSettingsAccountsRoute,
  AuthSettingsLogoutRoute: AuthSettingsLogoutRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthAccountsAccountIdRouteChildren {
  AuthAccountsAccountIdSettingsRoute: typeof AuthAccountsAccountIdSettingsRoute
  AuthAccountsAccountIdTeamRoute: typeof AuthAccountsAccountIdTeamRoute
  AuthAccountsAccountIdIndexRoute: typeof AuthAccountsAccountIdIndexRoute
}

const AuthAccountsAccountIdRouteChildren: AuthAccountsAccountIdRouteChildren = {
  AuthAccountsAccountIdSettingsRoute: AuthAccountsAccountIdSettingsRoute,
  AuthAccountsAccountIdTeamRoute: AuthAccountsAccountIdTeamRoute,
  AuthAccountsAccountIdIndexRoute: AuthAccountsAccountIdIndexRoute,
}

const AuthAccountsAccountIdRouteWithChildren =
  AuthAccountsAccountIdRoute._addFileChildren(
    AuthAccountsAccountIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthAccountsAccountIdRoute: typeof AuthAccountsAccountIdRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthAccountsAccountIdRoute: AuthAccountsAccountIdRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SentryTestRoute: SentryTestRoute,
  FollowInvitationErrorRoute: FollowInvitationErrorRoute,
  FollowInvitationIndexRoute: FollowInvitationIndexRoute,
  AuthLoginFromInvitationRoute: AuthLoginFromInvitationRoute,
  AuthResetPasswordSentRoute: AuthResetPasswordSentRoute,
  AuthSignupCompleteRoute: AuthSignupCompleteRoute,
  AuthSignupFromInvitationRoute: AuthSignupFromInvitationRoute,
  AuthVerifyEmailResendRoute: AuthVerifyEmailResendRoute,
  AuthVerifyEmailSentRoute: AuthVerifyEmailSentRoute,
  AuthVerifyEmailSuccessRoute: AuthVerifyEmailSuccessRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
  AuthChangeEmailConfirmSuccessRoute: AuthChangeEmailConfirmSuccessRoute,
  AuthSignupVerifyEmailSuccessRoute: AuthSignupVerifyEmailSuccessRoute,
  AuthVerifyEmailConfirmSuccessRoute: AuthVerifyEmailConfirmSuccessRoute,
  AuthSignupVerifyEmailIndexRoute: AuthSignupVerifyEmailIndexRoute,
  AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute:
    AuthChangeEmailConfirmUidb64SecretTokenInvalidRoute,
  AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute:
    AuthResetPasswordConfirmUidb64SecretTokenInvalidRoute,
  AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute:
    AuthVerifyEmailConfirmUidb64SecretTokenInvalidRoute,
  AuthChangeEmailConfirmUidb64SecretTokenIndexRoute:
    AuthChangeEmailConfirmUidb64SecretTokenIndexRoute,
  AuthResetPasswordConfirmUidb64SecretTokenIndexRoute:
    AuthResetPasswordConfirmUidb64SecretTokenIndexRoute,
  AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute:
    AuthVerifyEmailConfirmUidb64SecretTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
