#!/usr/bin/env bash

set -euo pipefail

until timeout 10 celery -A config.celery_app -b "${CELERY_BROKER_URL}" inspect ping; do
    >&2 echo "Celery workers have not fully booted yet."
done

echo 'Starting flower'

exec celery \
    -A config.celery_app \
    -b "${CELERY_BROKER_URL}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
