# Generated by Django 5.2.7 on 2025-10-21 04:32

import backend.accounts.models.accounts
import backend.accounts.models.users
import backend.base.storages
import backend.utils.model_indexes
import django.core.serializers.json
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "email_is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this User's email address been verified?",
                        verbose_name="Email Is Verified?",
                    ),
                ),
                (
                    "email_verified_as_of",
                    models.DateTimeField(
                        blank=True,
                        help_text="When was this User's email address verified?",
                        null=True,
                        verbose_name="Email Verified As Of",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="Is Staff?",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Potentially unselect this instead of deleting accounts.",
                        verbose_name="Is Active?",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "created_from",
                    models.CharField(
                        choices=[
                            ("direct_signup", "Direct Signup"),
                            ("account_invitation", "Account Invitation"),
                            ("admin", "Admin"),
                            ("create_default_admins", "Create Default Admins Command"),
                            ("create_superuser", "Create Superuser Command"),
                            ("other", "Other"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        editable=False,
                        help_text="Where was this User created from? At this time of writing this might only be used for analytics purposes. Regardless though, it's a potentially useful field to have for customer support, debugging, or similar, etc. purposes if that ever arises, etc., and has plenty of other use cases as well.",
                        max_length=31,
                        verbose_name="Created From",
                    ),
                ),
                (
                    "uploaded_profile_image",
                    models.ImageField(
                        blank=True,
                        max_length=511,
                        storage=backend.base.storages.get_default_public_media_storage,
                        upload_to=backend.accounts.models.users.user_profile_images_path,
                        verbose_name="Uploaded Profile Image",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", backend.accounts.models.users.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("personal", "Personal"), ("team", "Team")],
                        max_length=15,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Name"
                    ),
                ),
                (
                    "uploaded_profile_image",
                    models.ImageField(
                        blank=True,
                        max_length=511,
                        storage=backend.base.storages.get_default_public_media_storage,
                        upload_to=backend.accounts.models.accounts.account_profile_images_path,
                        verbose_name="Uploaded Profile Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("account_type__in", ["personal", "team"])),
                        name="act_act_at_cc",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Name"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("owner", "Owner")],
                        max_length=31,
                        verbose_name="Role",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Accepted At"
                    ),
                ),
                (
                    "declined_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Declined At"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "secret_token",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="Secret Token",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("email", "Email")],
                        max_length=31,
                        verbose_name="Delivery Method",
                    ),
                ),
                (
                    "first_sent_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="First Sent At",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Last Sent At"
                    ),
                ),
                (
                    "num_times_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Times Sent"
                    ),
                ),
                (
                    "delivery_data",
                    models.JSONField(
                        blank=True,
                        default=None,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Data specific to the Delivery Method used and/or just general additional data on the delivery.",
                        null=True,
                        verbose_name="Delivery Data",
                    ),
                ),
                (
                    "first_followed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="First Followed At",
                    ),
                ),
                (
                    "last_followed_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Last Followed At",
                    ),
                ),
                (
                    "num_times_followed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of Times Followed"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        related_query_name="invitation",
                        to="accounts.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        related_query_name="invitation_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Invited By",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        related_query_name="invitation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitations",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("owner", "Owner")],
                        max_length=31,
                        verbose_name="Role",
                    ),
                ),
                (
                    "last_selected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The last time the user created, switched to, or selected (etc.) this membership. This allows us to easily sort memberships by most recently selected.",
                        verbose_name="Last Selected At",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to="accounts.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        related_query_name="membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.CreateModel(
            name="UserAppState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Modified",
                    ),
                ),
                (
                    "current_membership_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Current Membership Id",
                    ),
                ),
                (
                    "current_membership_id_as_of",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Current Membership Id As Of",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_state",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User App State",
                "verbose_name_plural": "Users App States",
            },
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(("email", ""), _negated=True), name="act_usr_em_cc"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("email_is_verified", False),
                    ("email_verified_as_of__isnull", False),
                    _connector="OR",
                ),
                name="act_usr_eiv_eva_cc",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower(models.F("email")),
                name="act_usr_em_fuix",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["account", "expires_at"], name="act_ivt_ac_ea_ix"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                django.db.models.functions.text.Lower(models.F("email")),
                models.F("expires_at"),
                condition=models.Q(
                    ("accepted_at__isnull", True),
                    ("declined_at__isnull", True),
                    ("user_id__isnull", True),
                ),
                name="act_ivt_em_ea_pix",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=backend.utils.model_indexes.BrinOrFallbackIndex(
                autosummarize=True,
                fields=["created"],
                name="act_ivt_cr_ix",
                pages_per_range=128,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("accepted_at__isnull", True), ("declined_at__isnull", True)
                    ),
                    models.Q(
                        ("accepted_at__isnull", True), ("declined_at__isnull", False)
                    ),
                    models.Q(
                        ("accepted_at__isnull", False), ("declined_at__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="act_ivt_aa_da_cc",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["member", "owner"])),
                name="act_ivt_rl_cc",
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "last_selected_at"], name="act_mbs_us_ls_ix"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["member", "owner"])),
                name="act_mbs_rl_cc",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("account", "user"), name="act_mbs_ac_us_uix"
            ),
        ),
    ]
