volumes:
  better_base_ci_postgres_data: {}
  better_base_ci_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: better_base_ci_django
    container_name: better_base_ci_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.ci/.env
      - ./.envs/.dev/.django.env
      - ./.envs/.dev/.postgres.env
      - ./.envs/.dev/.redis.env
      - ./.envs/.dev/.celery.env
      - ./.envs/.dev/.docker.env
    command: /app/start

  postgres:
    build:
      context: .
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: better_base_prod_postgres
    container_name: better_base_ci_postgres
    volumes:
      - better_base_ci_postgres_data:/var/lib/postgresql:Z
      - better_base_ci_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.dev/.postgres.env

  redis:
    image: redis:8.6.1
    container_name: better_base_ci_redis

  celeryworker:
    <<: *django
    image: better_base_ci_celeryworker
    container_name: better_base_ci_celeryworker
    depends_on:
      - redis
      - postgres
    command: /app/start-celeryworker

  celerybeat:
    <<: *django
    image: better_base_ci_celerybeat
    container_name: better_base_ci_celerybeat
    depends_on:
      - redis
      - postgres
    command: /app/start-celerybeat

  flower:
    <<: *django
    image: better_base_ci_flower
    container_name: better_base_ci_flower
    command: /app/start-flower

  bun:
    build:
      context: .
      dockerfile: ./compose/dev/bun/Dockerfile
    image: better_base_ci_bun
    container_name: better_base_ci_bun
    depends_on:
      - django
    env_file:
      - ./.envs/.ci/.env
      - ./.envs/.dev/.docker.env
      - ./.envs/.dev/.django.env
      - ./.envs/.dev/.node.env
    environment:
      DEV_VITE_FROM_DOCKER: "true"
    command: bunx vite --port 4000 --strictPort --host 0.0.0.0
