volumes:
  better_base_dev_postgres_data: {}
  better_base_dev_postgres_data_backups: {}
  better_base_dev_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/dev/django/Dockerfile
    image: better_base_dev_django
    container_name: better_base_dev_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - ./backend:/app/backend:z
      - ./config:/app/config:z
      - ./frontend:/app/frontend:z
      - ./public:/app/public:z
    env_file:
      - ./.envs/.dev/.django.env
      - ./.envs/.dev/.postgres.env
      - ./.envs/.dev/.redis.env
      - ./.envs/.dev/.celery.env
      - ./.envs/.dev/.docker.env
      - ./.envs/.dev/.secrets.env
      - ./.envs/.dev/.specific.env
    ports:
      - "8020:8000"
    command: /app/start

  postgres:
    build:
      context: .
      dockerfile: ./compose/prod/postgres/Dockerfile
    image: better_base_prod_postgres
    container_name: better_base_dev_postgres
    volumes:
      - better_base_dev_postgres_data:/var/lib/postgresql
      - better_base_dev_postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev/.postgres.env
    ports:
      - "5452:5432"

  mailpit:
    image: axllent/mailpit:v1.29.4
    container_name: better_base_dev_mailpit
    ports:
      - "1045:1025"
      - "8045:8025"

  redis:
    image: redis:8.6.1
    container_name: better_base_dev_redis
    volumes:
      - better_base_dev_redis_data:/data
    ports:
      - "6399:6379"

  celeryworker:
    <<: *django
    image: better_base_dev_celeryworker
    container_name: better_base_dev_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /app/start-celeryworker

  celerybeat:
    <<: *django
    image: better_base_dev_celerybeat
    container_name: better_base_dev_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /app/start-celerybeat

  flower:
    <<: *django
    image: better_base_dev_flower
    container_name: better_base_dev_flower
    ports:
      - "5575:5555"
    command: /app/start-flower

  bun:
    build:
      context: .
      dockerfile: ./compose/dev/bun/Dockerfile
    image: better_base_dev_bun
    container_name: better_base_dev_bun
    depends_on:
      - django
    volumes:
      - ./backend:/app/backend:z
      - ./config:/app/config:z
      - ./frontend:/app/frontend:z
      - ./public:/app/public:z
    env_file:
      - ./.envs/.dev/.node.env
      - ./.envs/.dev/.docker.env
      - ./.envs/.dev/.django.env
      - ./.envs/.dev/.secrets.env
      - ./.envs/.dev/.specific.env
    environment:
      DEV_VITE_FROM_DOCKER: "true"
    command: bunx vite --port 4000 --strictPort --host 0.0.0.0
    ports:
      - "4020:4000"
