volumes:
  better_base_stage_redis_broker_data: {}
  better_base_stage_redis_cache_data: {}
  better_base_stage_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
      secrets:
        - vite_sentry_is_enabled
        - vite_sentry_auth_token
        - vite_sentry_dsn
        - vite_sentry_org
        - vite_sentry_project
        - vite_sentry_release
    image: better_base_stage_django
    platform: linux/x86_64
    depends_on:
      - redis_broker
      - redis_cache
    env_file:
      - ./.envs/.stage/.backend.env
      - ./.envs/.stage/.frontend.env
    command: /app/start
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2g"

  traefik:
    build:
      context: .
      dockerfile: ./compose/stage/traefik/Dockerfile
    image: better_base_stage_traefik
    depends_on:
      - django
    volumes:
      - better_base_stage_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
    restart: always

  redis_cache:
    image: redis:8.6.1
    container_name: redis_cache
    hostname: redis_cache
    volumes:
      - better_base_stage_redis_cache_data:/data
    command: [
        "redis-server",
        "--appendonly",
        "no",
        "--maxmemory",
        # About 256MB
        "268435456",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "384m"

  redis_broker:
    image: redis:8.6.1
    container_name: redis_broker
    hostname: redis_broker
    volumes:
      - better_base_stage_redis_broker_data:/data
    command: [
        "redis-server",
        "--appendonly",
        "no",
        "--maxmemory",
        # About 256MB
        "268435456",
        "--maxmemory-policy",
        "noeviction",
      ]
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "384m"

  celeryworker:
    <<: *django
    image: better_base_stage_celeryworker
    command: /app/start-celeryworker
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  celerybeat:
    <<: *django
    image: better_base_stage_celerybeat
    container_name: better_base_stage_celerybeat
    command: /app/start-celerybeat
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  flower:
    <<: *django
    image: better_base_stage_flower
    command: /app/start-flower
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

secrets:
  vite_sentry_is_enabled:
    environment: VITE_SENTRY_IS_ENABLED
  vite_sentry_auth_token:
    environment: VITE_SENTRY_AUTH_TOKEN
  vite_sentry_dsn:
    environment: VITE_SENTRY_DSN
  vite_sentry_org:
    environment: VITE_SENTRY_ORG
  vite_sentry_project:
    environment: VITE_SENTRY_PROJECT
  vite_sentry_release:
    environment: VITE_SENTRY_RELEASE
